- name: Creating ec2 instances and route53 records
  hosts: local
  connection: local
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: backend
      instance_type: t3.micro
      image_id: ami-09c813fb71547fc4f
      security_group: sg-0d746c47fa77fadc0
      state: present


