- name: Creating ec2 instances and route53 records
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0d746c47fa77fadc0
    domain_name: gangu.fun
    instances:
    - backend
    - frontend
  tasks:
  - name: Create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}"
      instance_type: t3.micro
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
    loop: "{{instances}}"
    register: ec2_info
  
  # - name: Print ec2 info 
  #   ansible.builtin.debug:
  #    msg: "{{ec2_info}}"

  # - name: Print public ip address
  #   ansible.builtin.debug:
  #     msg: "{{item.instances[0].public_ip_address}}"
  #   loop: "{{ec2_info.results}}"
     

  - name: update route53 records
    amazon.aws.route53:
      state: present
      zone:  "{{domain_name}}"
      record: "{{item.item}}.{{domain_name}}"
      type: A
      ttl: 1
      overwrite: true
      value: "{{item.instances[0].private_ip_address}}"
    loop: "{{ec2_info.results}}"

  - name: Route53 record update for frontend
    amazon.aws.route53: 
      state: present
      zone: "{{domain_name}}"
      record: "{{domain_name}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].public_ip_address}}"
      overwrite: true
    loop: "{{ec2_info.results}}"
    when: item.item=="frontend"

